services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 21258era#met
      MYSQL_DATABASE: airline_booking
    ports:
      - "3307:3306"   # Changed host port to 3307 to avoid conflicts
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping","-h","localhost"]
      interval: 10s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8881:8881"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airline_booking?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 21258era#met
